### ISSUE TITLE
Project no longer builds

### ISSUE THREAD

**Issue by pR0Ps** [izissise/nginx-explorer#18]
Log while following the steps listed in the readme:

```
~/tmp/nginx-explorer$ npm install bower
npm WARN deprecated bower@1.8.8: We don't recommend using Bower for new projects. Please consider Yarn and Webpack or Parcel. You can read how to migrate legacy project here: https://bower.io/blog/2017/how-to-migrate-away-from-bower/

> fsevents@1.2.9 install ~/tmp/nginx-explorer/node_modules/fsevents
> node install

node-pre-gyp WARN Using needle for node-pre-gyp https download
[fsevents] Success: "~/tmp/nginx-explorer/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node" is installed via remote
+ bower@1.8.8
added 694 packages from 313 contributors and audited 7681 packages in 14.314s
found 5 vulnerabilities (3 low, 2 high)
  run `npm audit fix` to fix them, or `npm audit` for details
~/tmp/nginx-explorer$ npm install
audited 7681 packages in 3.665s
found 5 vulnerabilities (3 low, 2 high)
  run `npm audit fix` to fix them, or `npm audit` for details
~/tmp/nginx-explorer$ npm run build

> nginx-explorer@0.0.1 build ~/tmp/nginx-explorer
> ./node_modules/gulp/bin/gulp.js build

assert.js:373
    throw err;
    ^

AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (~/tmp/nginx-explorer/node_modules/undertaker/lib/set-task.js:10:3)
    at Gulp.task (~/tmp/nginx-explorer/node_modules/undertaker/lib/task.js:13:8)
    at Object.<anonymous> (~/tmp/nginx-explorer/gulpfile.js:18:6)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at execute (~/tmp/nginx-explorer/node_modules/gulp/node_modules/gulp-cli/lib/versioned/^4.0.0/index.js:36:18) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nginx-explorer@0.0.1 build: `./node_modules/gulp/bin/gulp.js build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nginx-explorer@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     ~/.npm/_logs/2019-09-01T19_18_36_084Z-debug.log
~/tmp/nginx-explorer$
```

**Comment by izissise** [comment]
Thanks for bringing that up :)
I just pushed a commit that should fix the build

**Comment by izissise** [comment]
Hello, actually it wasn't building (file were not generated), it now completely fix and there is now a travis build that will push the files as github release :)
